### ISSUE TITLE
sizes[b] is not a function

### ISSUE THREAD

**Issue by radi-cho** [RSG-Group/rsg-components#11]
![image](https://user-images.githubusercontent.com/12954909/30001241-a0fa67fc-9090-11e7-9700-d5e32d6eba6f.png)

**Comment by retrixe** [comment]
Tracked it down, it's an error with your code. Feel free to fix it on master.

**Comment by radi-cho** [comment]
Okay, I will fix this later today. You learn for your examinations, @retrixe (This isn't sarcasm or mucks. I understand you - examinations are most important - rsg-components, website, everything can wait... examinations - no).

**Comment by radi-cho** [comment]
Okay fixed! 👍
...also ... Sorry for that delay (I opened this 5 days ago)

**Comment by radi-cho** [comment]
Again the same problem.
https://github.com/RSG-Group/rsg-components/blob/v3.0.0-alpha.5/src/RSGButton.js#L37
