### ISSUE TITLE
Add Input component

### ISSUE THREAD

**Issue by retrixe** [RSG-Group/rsg-components#15]
Replace it with Input.

**Comment by radi-cho** [comment]
The component is useless and insecure but I think it'll be fine to keep it under "deprecation".
I already left deprecation warning in the wiki. What do you think?

**Comment by retrixe** [comment]
Yes, but we need to replace it eventually.
Which is why Input.

**Comment by radi-cho** [comment]
We'll make an Input, but why to replace FormBasic? I meant to keep this component for now and make new component - Input.
