### ISSUE TITLE
Regarding CSS, prop names, wiki and move to inline styles

### ISSUE THREAD

**Issue by retrixe** [RSG-Group/rsg-components#2]
# CSS and Inline styles
~~While I was refactoring the codebase, I found a lot of ugly CSS code. It would be beneficial to refactor those. But I suggest using inline styles instead of CSS. This may ship with 3.0 as well.~~
**Updated APIs and inline styles shipped to 3.x with #3**
___
~~Also, we should drop support for HTML and move forward with pure JS. This would mean that we won't have to maintain separate CSS in `src`.~~

**Deprecated HTML support and CSS-dependent inline styles (RSGCheckbox and RSGProgressBar's CSS) rewritten to Less with #3**

# prop names
~~While reading the codebase, I found ugly, undocumented prop names like style1 and text1 ._. I propose to rename them to something better.~~
**Fixed in #1 and wiki is being updated with the newer APIs.**

~~Also, RSGProgressBar is horribly written and requires a rewrite, and so does RSGCheckbox.~~
**Refactored in #3 with inline styling and the rest**

# wiki
~~It's good, but it's quite ugly, which is why I propose a rewrite. Yes, rewrite.~~ No rewrite, it requires more active maintenance is all, I am now working on renovating the wiki.
___
Renovation of the wiki (ticked ones have corrected English, document the 3.x API and have been renovated):
- [x] Home
- [x] Transition
- [x] ProgressBar
- [x] FormBasic
- [x] Box
- [x] Button
- [x] Checkbox
- [x] Clock
- [x] Label
- [x] Sidebar
- [x] Bottom footer.

**Comment by Radi123** [comment]
# CSS and Inline styles
Ok, it's right.

# prop names
It'll be fine with better names - :smile:

# wiki
No probs with wiki. I know it isn't the most helpful. I created docs/ folder, because I want to improve it.
But the package is too heavy with docs. They  creating webpack mistakes too... And you have to delete them. Don't change the wiki page. Soon we will improve http://rsg-group.github.io and push docs there.

> Write your opinion soon. If you agree this close the issue.

**Comment by ibujs** [comment]
Okay, so I'll work on inline styles tomorrow, which will refactor the repository styles.
As for prop types, I will refactor those as well in #1
I will work on the Wiki and make it better. But your opinion on ditching support for HTML and CSS and write pure JS?

**Comment by Radi123** [comment]
# Okay @ibujs - PURE JS!!! :+1:

**Comment by Radi123** [comment]
About npm check your e-mail and slack tomorrow :smile:

**Comment by ibujs** [comment]
#3 will bring refactored CSS and Inline styles in addition to ditching HTML and CSS support. It will bring renamed prop-types as well. #4 should bring proper ES Module support by which 3.0 should be prepped and good to go with almost a complete rewrite of the codebase. Then I'll release 3.0.

**Comment by ibujs** [comment]
I will also work on spell correction and improved English throughout the Wiki and the project :slightly_smiling_face:

**Comment by Radi123** [comment]
@ibujs  OK. :1st_place_medal:

**Comment by ibujs** [comment]
prop names have been successfully fixed. I have asked for a code review on #1 again.

**Comment by ibujs** [comment]
I am slowly editing the wiki and correcting English page by page.
Home and RSGBox are done.

**Comment by Radi123** [comment]
What's happened with this issue, @retrixe ?

**Comment by radi-cho** [comment]
I added the following warning to all already ticked wiki pages (omit the sidebar and footer):
 > In version `3.0.0-beta.1` and later `RSG` is [removed](https://github.com/RSG-Group/rsg-components/pull/14) from the components so you have to use only `name` instead of `RSGname`

**Comment by radi-cho** [comment]
I think this is ready.
@retrixe - Take a look at the wiki. If there are problems reopen the issue.
