### ISSUE TITLE
RSGBox automatic sizing not working properly.

### ISSUE THREAD

**Issue by retrixe** [RSG-Group/rsg-components#6]
By default, RSGBox should take up as much space as possible, but it does not. Or at least enough size to accommodate the insides.

**Comment by radi-cho** [comment]
Wait...., send screenshot

**Comment by retrixe** [comment]
Look at the example code and see the height and width props. Remove them and see.

**Comment by radi-cho** [comment]
I saw this. ...?

![image](https://user-images.githubusercontent.com/12954909/29739553-19d3d526-8a49-11e7-8817-2c0c4637b1b9.png)

**Comment by retrixe** [comment]
I actually placed newlines between the 4 fields.
Instead, RSGBox puts them together.

**Comment by radi-cho** [comment]
### OK

**Comment by radi-cho** [comment]
In HTML you need `br` for new line, or using `<pre/>` tag

**Comment by radi-cho** [comment]
@retrixe Please test it again and close the issue... https://github.com/RSG-Group/rsg-components/commit/75615dab3e0880bf2418e4de177efed3ab3d3527

**Comment by retrixe** [comment]
Pretty sure it didn't work at that time either.

**Comment by retrixe** [comment]
`br` did not work since beginning. Also, we are talking JSX, I believe, which is syntactically different from HTML in some aspects. Box should scale automatically and height need not be specified, like a true div.

**Comment by retrixe** [comment]
It seems to work now. Close this.
